name: Deploy to GitHub Pages
on: workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/Iron
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Set environment
        run: |
          echo "VITE_GH_API_URL=https://api.github.com" >> .env
          echo "VITE_BASE_URL=/swivl-test-task/" >> .env
          echo "VITE_GH_PERSONAL_TOKEN=${{ secrets.GH_TOKEN }}" >> .env

      - name: Build
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
